{% set name = "python-oxmsg" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_oxmsg-{{ version }}.tar.gz
  sha256: b65c1f93d688b85a9410afa824192a1ddc39da359b04a0bd2cbd3874e84d4994

build:
  entry_points:
    - oxmsg = oxmsg.cli:oxmsg
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0.0
    - pip
  run:
    - python >=3.9
    - click
    - olefile
    - typing-extensions >=4.9.0

test:
  imports:
    - oxmsg
  commands:
    - pip check
    - oxmsg --help
  requires:
    - pip

about:
  home: https://github.com/scanny/python-oxmsg
  summary: Extract attachments from Outlook .msg files.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
