{% set name = "python-oxmsg" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_oxmsg-{{ version }}.tar.gz
  sha256: b65c1f93d688b85a9410afa824192a1ddc39da359b04a0bd2cbd3874e84d4994

build:
  entry_points:
    - oxmsg = oxmsg.cli:oxmsg
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=61.0.0
    - pip
    - wheel
  run:
    - python
    - click
    - olefile
    - typing-extensions >=4.9.0

test:
  imports:
    - oxmsg
  commands:
    - pip check
    - oxmsg --help
  requires:
    - pip
    - python

about:
  home: https://github.com/scanny/python-oxmsg
  summary: Extract attachments from Outlook .msg files.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: Extract attachments from Outlook .msg files.
  doc_url: https://scanny.github.io/python-oxmsg
  dev_url: https://github.com/scanny/python-oxmsg

extra:
  recipe-maintainers:
    - jan-janssen
